---
title: "About My Life"
description: |
  My Experience
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Desik Somasundaram

I am a master’s student in the Environmental Data Science program at the UCSB Bren School of Environmental Sciences and Management. I hold bachelor’s degrees in Environmental Engineering and Energy and Environmental Policy from University of Delaware. After graduation, I worked as a Water Resources Modeler/Programmer based in Malvern, PA for Environmental Resources Management (ERM). At ERM, I worked on a variety of projects ranging from oil spill and drill cuttings modelling to coastal imagery-based shoreline studies. My daily activities included the coding, debugging and use of FORTRAN-based hydrodynamic modelling suite named GEMSS (Generalized Environmental Modeling System for Surfacewaters). Executing the model often demanded the use of cloud computing through AWS and Microsoft Azure. To meet the data cleaning and processing needs, I developed scripts in Python (including ESRI ArcPy), R and UNIX command line to make our workflows more efficient. While in the industry, I also pursued my interests in sustainable development through the Micromaster’s Program in Data, Economics and Development Policy Program offered by MIT. Through attaining the Micromaster’s credential, focused on the challenges associated with addressing poverty, gender equality, education and the environment, I was inspired to further harness the power of data science to fulfill my life goal of working towards the UN Sustainable Development Goals.   
